version: '3.7'

volumes:
  zookeeper-1-data:
  zookeeper-1-datalog:
  zookeeper-1-logs:
  zookeeper-2-data:
  zookeeper-2-datalog:
  zookeeper-2-logs:
  kafka-1-data:
  kafka-1-secrets:
  kafka-2-data:
  kafka-2-secrets:
  kafka-3-data:
  kafka-3-secrets:

services:
  zookeeper-1:
    hostname: zookeeper-1
    container_name: zookeeper-1
    image: confluentinc/cp-zookeeper:latest
    restart: always
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper-1:2888:3888;2181 server.2=zookeeper-2:2888:3888;2181
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - zookeeper-1-data:/data
      - zookeeper-1-datalog:/datalog
      - zookeeper-1-logs:/logs
  zookeeper-2:
    hostname: zookeeper-2
    container_name: zookeeper-2
    image: confluentinc/cp-zookeeper:latest
    restart: always
    ports:
      - 2182:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper-1:2888:3888;2181 server.2=zookeeper-2:2888:3888;2181
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - zookeeper-1-data:/data
      - zookeeper-1-datalog:/datalog
      - zookeeper-1-logs:/logs

  # zookeeper-navigator:
  #   hostname: zookeeper-navigator
  #   container_name: zookeeper-navigator
  #   image: elkozmon/zoonavigator:1.1.2
  #   restart: always
  #   ports:
  #     - 9000:9000
  #   environment:
  #     HTTP_PORT: 9000
  #   depends_on:
  #     - zookeeper-1
  #     - zookeeper-2

  kafka-1:
    image: confluentinc/cp-kafka:latest
    hostname: kafka-1
    container_name: kafka-1
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${EXTERNAL_HOST}:9092,PLAINTEXT_HOST://${EXTERNAL_HOST}:9209
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ADVERTISED_HOST_NAME: ${EXTERNAL_HOST}
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: ${REPLICATION}
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      BOOTSTRAP_SERVERS: kafka-1:9092,kafka-2:9093,kafka-3:9094
    volumes:
      - kafka-1-data:/var/lib/kafka/data
      - kafka-1-secrets:/etc/kafka/secrets
    depends_on:
      - zookeeper-1
      - zookeeper-2

  kafka-2:
    image: confluentinc/cp-kafka:latest
    hostname: kafka-2
    container_name: kafka-2
    ports:
      - 9093:9093
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${EXTERNAL_HOST}:9093,PLAINTEXT_HOST://${EXTERNAL_HOST}:9203
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ADVERTISED_HOST_NAME: ${EXTERNAL_HOST}
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: ${REPLICATION}
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      BOOTSTRAP_SERVERS: kafka-1:9092,kafka-2:9093,kafka-3:9094
    volumes:
      - kafka-2-data:/var/lib/kafka/data
      - kafka-2-secrets:/etc/kafka/secrets
    depends_on:
      - zookeeper-1
      - zookeeper-2
  kafka-3:
    image: confluentinc/cp-kafka:latest
    hostname: kafka-3
    container_name: kafka-3
    ports:
      - 9094:9094
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${EXTERNAL_HOST}:9094,PLAINTEXT_HOST://${EXTERNAL_HOST}:9204
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ADVERTISED_HOST_NAME: ${EXTERNAL_HOST}
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: ${REPLICATION}
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      BOOTSTRAP_SERVERS: kafka-1:9092,kafka-2:9093,kafka-3:9094
    volumes:
      - kafka-3-data:/var/lib/kafka/data
      - kafka-3-secrets:/etc/kafka/secrets
    depends_on:
      - zookeeper-1
      - zookeeper-2
  # kafdrop:
  #   hostname: kafdrop
  #   container_name: kafdrop
  #   image: obsidiandynamics/kafdrop:3.30.0
  #   ports:
  #     - 9001:9000
  #   environment:
  #     KAFKA_BROKERCONNECT: 'kafka-1:9092,kafka-2:9093'
  #     JVM_OPTS: '-Xms32M -Xmx64M'
  #   depends_on:
  #     - zookeeper-1
  #     - zookeeper-2
  #     - kafka-1
  #     - kafka-2
# services:
#   zookeeper:
#     image: confluentinc/cp-zookeeper:latest
#     environment:
#       ZOOKEEPER_SERVER_ID: 1
#       ZOOKEEPER_CLIENT_PORT: 2181
#       ZOOKEEPER_TICK_TIME: 2000
#       ZOOKEEPER_INIT_LIMIT: 5
#       ZOOKEEPER_SYNC_LIMIT: 2
#     ports:
#       - "22181:2181"
#     volumes:
#       - zookeeper-1-data:/data
#       - zookeeper-1-datalog:/datalog
#       - zookeeper-1-logs:/logs

#   kafka:
#     image: confluentinc/cp-kafka:latest
#     depends_on:
#       - zookeeper
#     ports:
#       - "29092:29092"
#     environment:
#       KAFKA_BROKER_ID: 1
#       KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
#       KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
#       KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
#       KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
#       KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#       KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
#     volumes:
#       - kafka-1-data:/var/lib/kafka/data
#       - kafka-1-secrets:/etc/kafka/secrets
